spring:
  application:
    name: sajamart

  lifecycle:
    timeout-per-shutdown-phase: 15s

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

  h2:
    console:
      enabled: true

  config:
    import: optional:configserver:http://localhost:9001

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/master

# WAS 설정
server:
  port: 9000
  shutdown: graceful

# 로그 설정
logging:
  file:
    name: /logs/application.log
  logback:
    rollingpolicy:
      max-history: 7
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
