spring:
  application:
    name: sajamart

  lifecycle:
    timeout-per-shutdown-phase: 15s

  profiles:
    active: dev

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

  h2:
    console:
      enabled: true

  config:
    import: optional:configserver:http://localhost:9001

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/master

server:
  port: 9000
  shutdown: graceful