spring:
  application:
    name: sajamart
  profiles:
    active: dev

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

  h2:
    console:
      enabled: true

  config:
    import: optional:configserver:http://localhost:9001